name: naver_maps_flutter
description: A Flutter plugin that provides a Naver Maps widget.
version: 0.0.1
author: barogo
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.barogo.plugins.navermaps
        pluginClass: NaverMapsPlugin
      ios:
        pluginClass: NaverMapsPlugin